### ISSUE TITLE
HomeAssistant ESPHome Ratgo GDO Firmware Update 2023.12.7 fails

### ISSUE THREAD

**Issue by wesf99** [ratgdo/esphome-ratgdo#177] opened 2024-01-18 04:26 UTC
Home assistant update fails while updating Ratgo Garage Door Firmware from 2023.12.6 to 2023.12.7.

Initial Error "Failed to call service update/install. Error updating ratgdov25-8e63d1.yaml via OTA. Try agina in ESPHome dashbaord for more information."

Logs message " Error binary size: Error: ESP does not have enough space to store OTA file. Please try flashing a minimal firmware (remove everything except ota)"

Also getting messages about "OTA duration taking to long" and "Component preferences took a long time for an operation" (while opening and closing the door)

Log's attached.
[logs_ratgdov25-8e63d1_run (2).txt](https://github.com/ratgdo/esphome-ratgdo/files/13972080/logs_ratgdov25-8e63d1_run.2.txt)
[logs_ratgdov25-8e63d1_logs (2).txt](https://github.com/ratgdo/esphome-ratgdo/files/13972081/logs_ratgdov25-8e63d1_logs.2.txt)

**Comment by rlowens** [comment] 2024-01-18 05:05
Duplicate of https://github.com/ratgdo/esphome-ratgdo/issues/155

**Closed** 2024-01-18 05:20 UTC
