### ISSUE TITLE
Single Relay Dry Contacts to Toggle Door

### ISSUE THREAD

**Issue by heffneil** [ratgdo/esphome-ratgdo#285] opened 2024-06-05 12:37 UTC
Is there a way to toggle a door with a single set of dry contacts?  I am prewired for my previous door and only have one relay to toggle the old operator.  I don't see a set of toggle options for the dry contact inputs.

**Comment by PaulWieland** [comment] 2024-06-05 12:55
duplicate of #214

**Comment by PaulWieland** [comment] 2024-07-12 15:21
#307

**Closed by PaulWieland** 2024-07-12 15:21 UTC
