### ISSUE TITLE
Log spammed with `Collision detected, waiting to send packet`

### ISSUE THREAD

**Issue by ptr727** [ratgdo/esphome-ratgdo#111] opened 2023-11-16 01:16 UTC
With the device tethered for programming, but not connected to the opener yet, the log gets spammed with thousands of `Collision detected, waiting to send packet` events, that result in the esphome dashboard becoming non-responsive.

Code is [here](https://github.com/ratgdo/esphome-ratgdo/blob/e36225cfcee9ae7bdb164afceb97d7e0b15634b0/components/ratgdo/ratgdo.cpp#L467)

Maybe some preamble is required to either prevent the high rate of logs or wait for input to be connected.

Using a ratgdo v2.5 with a D1 mini.

**Comment by bdraco** [comment] 2023-12-10 23:39
duplicate of https://github.com/ratgdo/esphome-ratgdo/issues/47

Its not designed to function without being connected to the GDO

**Closed by bdraco** 2023-12-10 23:39 UTC
