### ISSUE TITLE
Missing Feature: UL325 Safety Standard Compliance for Remote Close (warning beep before delayed close)

### ISSUE THREAD

**Issue by cgbale** [ratgdo/esphome-ratgdo#227] opened 2024-02-14 23:07 UTC
ratgdo is missing a critical MyQ safety feature that sounds the keypad beep alarm for approximately 10 seconds before closing the garage door. It would be great if ratgdo could send the same command as MyQ to initiate the "remote close warning and delay" feature instead of immediately closing the garage door without warning.

I almost experienced a related problem when a remote close command was sent just before I was going to back out of the garage. I almost backed into the garage door as it lowered because there was no warning or delay, and the descending door was not visible from the car until was half closed.

The UL325 safety standard specifies that a garage door must use a siren and/or strobe to prevent and/or warn of "pending entrapment." This is required for garage doors when they are closing, and for gates when both opening and closing. LiftMaster/Chamberlain uses the beeping keypad to comply with this safety standard.

**Comment by rlowens** [comment] 2024-02-14 23:33
Duplicate of https://github.com/ratgdo/esphome-ratgdo/issues/42

**Closed** 2024-02-14 23:34 UTC
